#ifndef PICO53_PICOI2C_H
#define PICO53_PICOI2C_H

#include <stdint.h>

#include "hardware/i2c.h"
#include "si5351.h"

#define CLK0_CTRL_DEFAULT 0xCF
#define CLK1_CTRL_DEFAULT 0xCF
#define CLK2_CTRL_DEFAULT 0xEF

/**
 * Initialize a Si5351 chip connected to the specified interface to a known state.
 * All outputs disabled and powered off with 8mA drive strength
 * OMD set to integer mode
 * CLK0 and CLK1 to PLLA
 * CLK2 to PLLB
 * @param si5351_addr I2C address for the chip
 * @param i2c_interface I2C interface connected to the same bus as the chip
 */
void si5351_init(uint8_t si5351_addr, struct i2c_inst *i2c_interface);

/**
 * Set and enable the desired output to the frequency generated by the specified configuration.
 * @param config Configuration for the feedback and output Multisynth dividers
 * @param output Output pin to be set
 */
void si5351_set_freq(struct Si5351Config *config, enum Multisynth ms);

/**
 * Turn on or off the output associated with the specified Multisynth
 * @param ms The clock associated with this Multisynth will be modified
 * @param status 0: OFF - otherwise ON
 */
void si5351_set_out(enum Multisynth ms, uint8_t status);

/**
 * Enable or disable the clock associated with the specified Multisynth
 * @param ms The clock associated with this Multisynth will be modified
 * @param status 0: disabled - otherwise enabled
 * @param invert Whether to invert (1) or not (0) the clock's output
 */
void si5351_en_clk(enum Multisynth ms, uint8_t status, uint8_t invert);

/**
 * Write to a specified register
 * @param reg Register to be written
 * @param value Value to be written into the register
 * @return The result of the write operation, as returned by Pico's SDK
 */
int si5351_write(uint8_t reg, uint8_t value);

/**
 * Read data from a specified register
 * @param reg Register to read the data from
 * @return The result of the read operation, as returned by Pico's SDK
 */
int si5351_read(uint8_t reg);

#endif  // PICO53_PICOI2C_H
