#ifndef PICO53_PICOI2C_H
#define PICO53_PICOI2C_H

#include <stdint.h>

#include "hardware/i2c.h"
#include "si5351.h"

#define CLK0_CTRL_DEFAULT 0xCF
#define CLK1_CTRL_DEFAULT 0xCF
#define CLK2_CTRL_DEFAULT 0xEF

/**
 * Initialize a Si5351 chip connected to the specified interface to a known state.
 * All outputs disabled and powered off with 8mA drive strength
 * OMD set to integer mode
 * CLK0 and CLK1 to PLLA
 * CLK2 to PLLB
 * @param si5351_addr I2C address for the chip
 * @param i2c_interface I2C interface connected to the same bus as the chip
 */
void si5351_init(uint8_t si5351_addr, struct i2c_inst *i2c_interface);

/**
 * Set and enable the desired output to the frequency generated by the specified configuration.
 * @param config Configuration for the feedback and output Multisynth dividers
 * @param output Output pin to be set
 */
void si5351_set_freq(struct Si5351Config *config, enum Multisynth ms);

/**
 *
 * @param ms
 * @param status
 */
void si5351_set_out(enum Multisynth ms, uint8_t status);

#endif  // PICO53_PICOI2C_H
